name: Tech Singularity
markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
safe: true
lsi: false
pygments: true
url: http://blog.michaelportnoy.ca
analytics :
    provider : google
    google :
        tracking_id : 'UA-48976841-1'
    getclicky :
    site_id :
